name: nyobadoang
description: "A new Flutter project."
publish_to: 'none' # Change this if you plan to publish to pub.dev
version: 0.1.0+1 # Added build number

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: 
  permission_handler: ^10.0.0
  geolocator: ^9.0.0
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.2
  shared_preferences: ^2.0.15
  printing: ^5.10.1
  pdf: ^3.8.1 
  flutter_riverpod: ^2.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Add assets if needed, uncomment the line below if you plan to use assets
  # assets:
  #   - assets/
